package minionModel;

public interface MinionGlobals {

    public final boolean DEBUG = false; // print debug-info during translation process
    public final boolean PRINT_MESSAGE = true;  // print messages during translation process

    public final String MINION_VERSION = "MINION 1";
    public final double  MINION_VERSION_NUMBER = 0.3;

    public final boolean ENABLE_VARIABLE_ORDERING = false;  // enable fixed variable ordering
                                                            // (the order they appear)    
    public final boolean ENABLE_VALUE_ORDERING = false; // enable ascending value ordering

    public final String MINION_HEADER = "\n# This file has been automatically generated by the"+
    						"Essence'-> Minion translator\n# \n"+
    						"# Input file for Minion built for Version "+MINION_VERSION_NUMBER+
    						"\n#    http://sourceforge.net/projects/minion\n#" ;
    
    public final boolean USE_WATCHED_LITERALS = true;
    public final boolean USE_DISCRETE_VARIABLES = false;
}
