
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 12 13:38:37 GMT 2007
//----------------------------------------------------

package translator.essencePrimeParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 13;
  public static final int ATMOST = 4;
  public static final int POWER = 51;
  public static final int MULT = 49;
  public static final int FIND = 12;
  public static final int UMINUS = 52;
  public static final int BE_NEW_TYPE = 7;
  public static final int INTEGER = 63;
  public static final int GREATER = 45;
  public static final int LPAREN = 30;
  public static final int INT = 16;
  public static final int LEXGREATER = 59;
  public static final int GIVEN = 14;
  public static final int MINUS = 48;
  public static final int LESS = 43;
  public static final int WHERE = 29;
  public static final int BAR = 40;
  public static final int MATRIX_INDEXED_BY = 18;
  public static final int RPAREN = 31;
  public static final int LEXLEQ = 60;
  public static final int NOT = 55;
  public static final int AND = 53;
  public static final int OR = 54;
  public static final int COMMA = 38;
  public static final int SUCH_THAT = 25;
  public static final int DOTDOT = 37;
  public static final int GEQ = 46;
  public static final int PLUS = 47;
  public static final int IF = 56;
  public static final int MIN = 22;
  public static final int ALLDIFF = 2;
  public static final int DOT = 36;
  public static final int OF = 24;
  public static final int EOF = 0;
  public static final int TABLE = 27;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int ATLEAST = 3;
  public static final int MINIMISING = 21;
  public static final int EXISTS = 9;
  public static final int NEQ = 42;
  public static final int EQ = 41;
  public static final int LETTING = 17;
  public static final int LBRACK = 34;
  public static final int BE_DOMAIN = 6;
  public static final int HEADER = 15;
  public static final int COLON = 39;
  public static final int LBRACE = 32;
  public static final int BE = 5;
  public static final int RBRACK = 35;
  public static final int ENUM = 8;
  public static final int ELEMENT = 10;
  public static final int RBRACE = 33;
  public static final int LEQ = 44;
  public static final int SUM = 26;
  public static final int LEXGEQ = 61;
  public static final int FALSE = 11;
  public static final int MAXIMISING = 19;
  public static final int DIVISION = 50;
  public static final int MAX = 20;
  public static final int LEXLESS = 58;
  public static final int IFF = 57;
  public static final int IDENTIFIER = 62;
  public static final int OCCURRENCE = 23;
}

