
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 30 10:05:40 GMT 2007
//----------------------------------------------------

package translator.essencePrimeParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 13;
  public static final int ATMOST = 4;
  public static final int POWER = 54;
  public static final int MULT = 52;
  public static final int FIND = 12;
  public static final int UMINUS = 55;
  public static final int BE_NEW_TYPE = 7;
  public static final int INTEGER = 66;
  public static final int GREATER = 48;
  public static final int LPAREN = 33;
  public static final int INT = 16;
  public static final int LEXGREATER = 62;
  public static final int GIVEN = 14;
  public static final int MINUS = 51;
  public static final int LESS = 46;
  public static final int PARAM = 25;
  public static final int WHERE = 32;
  public static final int BAR = 43;
  public static final int MATRIX_INDEXED_BY = 18;
  public static final int RPAREN = 34;
  public static final int LEXLEQ = 63;
  public static final int NOT = 58;
  public static final int AND = 56;
  public static final int IS = 19;
  public static final int OR = 57;
  public static final int COMMA = 41;
  public static final int SUCH_THAT = 28;
  public static final int DOTDOT = 40;
  public static final int GEQ = 49;
  public static final int PLUS = 50;
  public static final int IF = 59;
  public static final int MIN = 24;
  public static final int ALLDIFF = 2;
  public static final int DOT = 39;
  public static final int OF = 27;
  public static final int EOF = 0;
  public static final int TABLE = 30;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int ATLEAST = 3;
  public static final int MINIMISING = 23;
  public static final int EXISTS = 9;
  public static final int NEQ = 45;
  public static final int EQ = 44;
  public static final int LETTING = 17;
  public static final int LBRACK = 37;
  public static final int BE_DOMAIN = 6;
  public static final int HEADER = 15;
  public static final int COLON = 42;
  public static final int LBRACE = 35;
  public static final int BE = 5;
  public static final int RBRACK = 38;
  public static final int ENUM = 8;
  public static final int IS_DOMAIN = 20;
  public static final int ELEMENT = 10;
  public static final int RBRACE = 36;
  public static final int LEQ = 47;
  public static final int SUM = 29;
  public static final int LEXGEQ = 64;
  public static final int FALSE = 11;
  public static final int MAXIMISING = 21;
  public static final int DIVISION = 53;
  public static final int MAX = 22;
  public static final int LEXLESS = 61;
  public static final int IFF = 60;
  public static final int IDENTIFIER = 65;
  public static final int OCCURRENCE = 26;
}

