
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 23 14:13:54 BST 2007
//----------------------------------------------------

package translator.essencePrimeParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FORALL = 13;
  public static final int ATMOST = 4;
  public static final int POWER = 49;
  public static final int MULT = 47;
  public static final int FIND = 12;
  public static final int UMINUS = 50;
  public static final int BE_NEW_TYPE = 7;
  public static final int INTEGER = 61;
  public static final int GREATER = 43;
  public static final int LPAREN = 28;
  public static final int LEXGREATER = 57;
  public static final int GIVEN = 14;
  public static final int MINUS = 46;
  public static final int LESS = 41;
  public static final int WHERE = 27;
  public static final int BAR = 38;
  public static final int MATRIX_INDEXED_BY = 17;
  public static final int RPAREN = 29;
  public static final int LEXLEQ = 58;
  public static final int NOT = 53;
  public static final int AND = 51;
  public static final int OR = 52;
  public static final int COMMA = 36;
  public static final int SUCH_THAT = 24;
  public static final int DOTDOT = 35;
  public static final int GEQ = 44;
  public static final int PLUS = 45;
  public static final int IF = 54;
  public static final int MIN = 21;
  public static final int ALLDIFF = 2;
  public static final int DOT = 34;
  public static final int OF = 23;
  public static final int EOF = 0;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int ATLEAST = 3;
  public static final int MINIMISING = 20;
  public static final int EXISTS = 9;
  public static final int NEQ = 40;
  public static final int EQ = 39;
  public static final int LETTING = 16;
  public static final int LBRACK = 32;
  public static final int BE_DOMAIN = 6;
  public static final int HEADER = 15;
  public static final int COLON = 37;
  public static final int LBRACE = 30;
  public static final int BE = 5;
  public static final int ENUM = 8;
  public static final int RBRACK = 33;
  public static final int ELEMENT = 10;
  public static final int RBRACE = 31;
  public static final int LEQ = 42;
  public static final int SUM = 25;
  public static final int LEXGEQ = 59;
  public static final int FALSE = 11;
  public static final int MAXIMISING = 18;
  public static final int DIVISION = 48;
  public static final int MAX = 19;
  public static final int LEXLESS = 56;
  public static final int IFF = 55;
  public static final int IDENTIFIER = 60;
  public static final int OCCURRENCE = 22;
}

