
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 28 14:25:56 BST 2008
//----------------------------------------------------

package translator.xcsp2ep.mapper.functionalsParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 16;
  public static final int AND = 4;
  public static final int NE = 18;
  public static final int LT = 13;
  public static final int NEG = 19;
  public static final int RPAREN = 28;
  public static final int OR = 21;
  public static final int NOT = 20;
  public static final int IDENTIFIER = 30;
  public static final int POW = 22;
  public static final int TRUE = 24;
  public static final int IF = 10;
  public static final int LPAREN = 27;
  public static final int GT = 9;
  public static final int LE = 12;
  public static final int SUB = 23;
  public static final int COMMA = 29;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int ABS = 2;
  public static final int ADD = 3;
  public static final int FALSE = 7;
  public static final int GE = 8;
  public static final int error = 1;
  public static final int IFF = 11;
  public static final int EQ = 6;
  public static final int MIN = 15;
  public static final int INTEGER = 31;
  public static final int XOR = 26;
  public static final int MAX = 14;
  public static final int MUL = 17;
  public static final int UMINUS = 25;
}

